apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kurl-secrets
  namespace: default
spec:
  encryptedData:
    BUGSNAG_KEY: AgC0sRe5cGvrmt+siwSm1SjX+BV+o7CSjVRoT6BWyxTLraSuuJEzqVsIqOh33jqGJ79/NbyhM9afOEkSlyJLw6NdAJwVQRDlNq3zvnAaK/giI5Xl+UvrKSdWzHSMxQiZxS/3wgXhbJV4VkjNszA1MzAxpklO+NOSGTHeMb0UujzQzbnLTrf4oKbzN3OQB0c722KtDJoPcnNtmd1vxDvI5HghNI4zLx/hANTlNtvH5cvQgDwQ6omLH50JszCwYnHpQTzwwSoWn5uPm8jCavXo4S4qnYrcomTokc9jEg8kx1H/gFuO2D1On5nVJsre5iZSNnnNPgiuoFytyC49dtWYvrmvUZK5O4NDRfx38h7HAMSxCuWsRS3X3qk21AC0mLEB2EkmGsg3TKx5oJDJ6ucvn7o+10K0ksiQkQXEdlROK9hX1Z6h3pDKSRi0/qPQr0T5MvwlPMTCFv207mWFDBJtY3pV1U9NSo9yUDWhScRggsSU2c3mUlc0Badk3gndUOCJrJaWxacOciz57ZVwOzDMAT/HrJQv543Xc3nXxPEXvNerhRNlfAUFqtMYwsEHzci/6l+wbf5LROhPkQGejdqvQRFXmgBJCuIb7veDM3yy4irp4fRrd5yQdVFBB/Cj88BJalGWzIuHcm9yv3x30YpwGDzV/5jeWWlSffCaLSpOXZ0BBk1cPik1UQofzGwcYd4N9cid6X4qj+6kgpq+h6vnIsAHZ/wc28X5bBbg+Bfrv8mrPA==
  template:
    metadata:
      creationTimestamp: null
      name: kurl-secrets
      namespace: default
status: {}

