FROM schemahero/schemahero:0.14.0-alpha.1 as schemahero
WORKDIR /go/src/github.com/replicatedhq/kurl-api/migrations

USER root
RUN apt-get update && \
    apt-get install -y build-essential && \
    rm -rf /var/lib/apt/lists/*
USER schemahero

COPY . .
