---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kurl-mysql-config
data:
  docker.cnf: |-
    [mysqld]
    skip-host-cache
    skip-name-resolve
    secure_file_priv = ""

    # this is needed because node mysql package does not support caching_sha2_password
    default-authentication-plugin=mysql_native_password

    # matching staging and prod servers
    sql_mode=NO_ENGINE_SUBSTITUTION
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kurl-mysql
spec:
  selector:
    matchLabels:
      app: kurl-mysql
  serviceName: kurl-mysql
  template:
    metadata:
      labels:
        app: kurl-mysql
    spec:
      initContainers:
        - name: "remove-lost-found"
          image: "busybox:1.33.0"
          imagePullPolicy: IfNotPresent
          command:  ["rm", "-fr", "/var/lib/mysql/lost+found"]
          volumeMounts:
            - name: datadir
              mountPath: /var/lib/mysql
      containers:
        - name: mysql
          image: mysql:8.0.28
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_ROOT_HOST
              value: '%'
            - name: MYSQL_USER
              value: replicated
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: replicated
          ports:
            - name: mysql
              containerPort: 3306
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}
            initialDelaySeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
          volumeMounts:
            - name: datadir
              mountPath: /var/lib/mysql
            - name: config
              mountPath: /etc/mysql/conf.d
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: datadir
        - name: config
          configMap:
            name: kurl-mysql-config


  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kurl-mysql
  labels:
    app: kurl-mysql
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: kurl-mysql
