apiVersion: v1
kind: Service
metadata:
  name: kurl
  labels:
    app: kurl
spec:
  type: NodePort
  ports:
    - name: server
      nodePort: 30092
      port: 3001
      targetPort: server
  selector:
    app: kurl
