name: build-test

on: [ pull_request ]

jobs:

  validate-go-mod:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - run: go mod tidy -compat=1.17

  build-web:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: make deps test build

  build-server:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: make go-test build/bin/server

  build-test-success:
    runs-on: ubuntu-latest
    needs:
    - validate-go-mod
    - build-web
    - build-server
    steps:
    - run: echo "::notice ::build test success"

  pact-provider-verify:
    uses: ./.github/workflows/pact-provider-verify.yaml
    with:
      PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: false
    secrets:
      PACT_BROKER_BASE_URL: https://replicated.pactflow.io
      # read only token, safe
      PACT_BROKER_TOKEN: W2y60iAYJbPuWSL_wsObzw
  
  pact-can-i-deploy:
    runs-on: ubuntu-latest
    needs:
      - pact-provider-verify
    env:
      PACT_RETRY_WHILE_UNKNOWN: '0'
      PACT_BROKER_CAN_I_DEPLOY_DRY_RUN: 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: replicatedhq/action-install-pact@main
      - run: make -C pact can-i-deploy
